# Generated by Django 4.2.4 on 2023-12-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=50)),
            ],
        ),
    ]
